---
- name: restart ntp
  ansible.builtin.systemd:
    name: systemd-timesyncd
    daemon_reload: yes
    state: restarted

- name: apply netplan
  ansible.builtin.command: netplan apply
  become: yes